### ISSUE TITLE
Vsnip-Integ

### ISSUE THREAD

**Issue by hydrasho** [yegappan/lsp#182] opened 2023-03-23 21:51 UTC
Hello again ! I can't make the link between this plugin and vsnip-integ, the vsnip-integ doc is empty... but specify that this plugin is compatible, maybe add a section on it in the readme ? thanks !

**Comment by yegappan** [comment] 2023-03-25 01:36
Did you set the LSP plugin "snippetSupport" option to v:true?  How are you adding the LSP and vsnip plugins?  In my local setup the vsnip plugin works with the LSP plugin with the "snippetSupport" option set to v:true.

**Comment by greeschenko** [comment] 2023-03-31 16:59
hello, have same problem

my config 

`
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

......

var lspServers = [
		     {
			'filetype': ['javascript', 'typescript'],
			'path': 'typescript-language-server',
			'args': ['--stdio']
		     },
		     {
			'filetype': ['go', 'gomod'],
                        'path': '/go/bin/gopls',
			'args': [],
		     }
		   ]


lsp#options#OptionsSet({
    showDiagWithVirtualText: v:true,
    diagVirtualTextHL: 'WarningMsg',
    showInlayHints: v:false,
    showDiagOnStatusLine: v:false,
    showDiagInPopup: v:false,
    diagLineHL: "NONE",
    completionMatcher: "fuzzy",
    snippetSupport: v:true,
})

lsp#lsp#AddServer(lspServers)


`

I see that LSP servers do not return any data with item->get('insertTextFormat', 1) == 2

**Comment by yegappan** [comment] 2023-03-31 23:27
Can you provide some sample code and the sequence of steps to reproduce the problem?

**Comment by greeschenko** [comment] 2023-04-02 09:44
``Hello, yes I am using 'Plug' for install
I have this problem with both my LSP servers typescript-language-server and gopls 
if I add my own snippet to vim-vsnip it work but this snippet not exist in completion list and lsp snippets also not exist in completion list 
Maybe I need to add more options to the LSP server

:LspShowServerCapabilities

```
'typescript-language-server' Language Server Capabilities
=========================================================
callsProvider: true
codeActionProvider: {'codeActionKinds': ['source.organizeImports.ts-ls']}
completionProvider: {'resolveProvider': true, 'triggerCharacters': ['.', '"', '''', '/', '@', '<']}
definitionProvider: true
documentFormattingProvider: true
documentHighlightProvider: true
documentRangeFormattingProvider: true
documentSymbolProvider: true
executeCommandProvider: {'commands': ['_typescript.applyWorkspaceEdit', '_typescript.applyCodeAction', '_typescript.applyRefactoring', '_typescript.organizeImports', '_typescript.applyRenameFile']}
foldingRangeProvider: true
hoverProvider: true
implementationProvider: true
referencesProvider: true
renameProvider: true
signatureHelpProvider: {'triggerCharacters': ['(', ',', '<']}
textDocumentSync: 2
typeDefinitionProvider: true
workspaceSymbolProvider: true
```

**Comment by maximyurevich** [comment] 2023-04-04 09:05
> Hello, yes I am using 'Plug' for install I have this problem with both my LSP servers typescript-language-server and gopls if I add my own snippet to vim-vsnip it work but this snippet not exist in completion list and lsp snippets also not exist in completion list Maybe I need to add more options to the LSP server
> 
> :LspShowServerCapabilities
> 
> ```
> 'typescript-language-server' Language Server Capabilities
> =========================================================
> callsProvider: true
> codeActionProvider: {'codeActionKinds': ['source.organizeImports.ts-ls']}
> completionProvider: {'resolveProvider': true, 'triggerCharacters': ['.', '"', '''', '/', '@', '<']}
> definitionProvider: true
> documentFormattingProvider: true
> documentHighlightProvider: true
> documentRangeFormattingProvider: true
> documentSymbolProvider: true
> executeCommandProvider: {'commands': ['_typescript.applyWorkspaceEdit', '_typescript.applyCodeAction', '_typescript.applyRefactoring', '_typescript.organizeImports', '_typescript.applyRenameFile']}
> foldingRangeProvider: true
> hoverProvider: true
> implementationProvider: true
> referencesProvider: true
> renameProvider: true
> signatureHelpProvider: {'triggerCharacters': ['(', ',', '<']}
> textDocumentSync: 2
> typeDefinitionProvider: true
> workspaceSymbolProvider: true
> ```

Your ultisnips integration with vim-snippets plugins works, vsnip-integ with friendly snippets doesn't. Strange

**Comment by greeschenko** [comment] 2023-04-04 19:58
Hello, Yes, ultisnip integration work because it get snippets directly from ultisnip plugin function, but I can`t get snippet text for preview yet. 
vsnip-integ should use snippets from LSP server like vcode  but maybe it not work with all LSP servers or need some options

**Comment by girishji** [comment] 2023-06-01 09:23
I have a PR to address this #332

**Comment by maximyurevich** [comment] 2023-06-02 15:45
> I have a PR to address this #332

vim-vsnip-integ needed now?

**Comment by Shane-XB-Qian** [comment] 2023-06-03 08:34
> vim-vsnip-integ needed now?

let me help to answer: yes, should be, #332 just impl some integ code into this lsp base, which maybe should/can put into 'integ' codebase as well.

**Comment by hydrasho** [comment] 2023-06-15 01:15
now that vim-vsnip-integ has been merged, this commit should be closed?

**Comment by Shane-XB-Qian** [comment] 2023-06-17 16:16
@hydrasho  if you find anything else, or closing then.. i guess so. :smile:

**Closed** 2023-06-18 13:59 UTC
