### ISSUE TITLE
omnicompletion of function after opening parentheses

### ISSUE THREAD

**Issue by Konfekt** [yegappan/lsp#462] opened 2024-02-25 14:39 UTC
After having passed `autoComplete: v:false` to `LspOptionsSet()`, then in Python (or any other language using functions whose arguments are passed inside parentheses), omni-completing

```
print(
```

gives

```
Error found executing function LspOmniFunc:
line   42:
E716: Key not present in Dictionary: "completeItems"
```

If instead `print` is completed to `print(`, then completing `print(` completes to `print(print`

**Comment by yegappan** [comment] 2024-02-25 16:30
I committed 0f774f942d8dc351661d1609ada97e6e826d71b4 to address this issue.  Can you try the latest plugin?

**Comment by Konfekt** [comment] 2024-02-25 19:21
Thank you! Now we advanced one line as it spits out

```
Trovato errore eseguendo function LspOmniFunc:
line   43:
E716: Key missing in Dictionary: "omniCompleteKeyword"
```

**Comment by yegappan** [comment] 2024-02-26 01:56
I am not able to reproduce this issue with a python file and the pylsp language server.  Can you attach the language server configuration, LSP plugin configuration, a sample python file and the sequence of steps to reproduce this problem?

**Comment by Konfekt** [comment] 2024-02-26 10:11
Calling

```
vim --clean -u ~/.vim/viminrc
```

with `~/.vim/viminrc` reading

```vim
set nocompatible
language messages en_US  " To avoid scrambled non english letters.

let &rtp = '~/.vim/plugged/lsp/' . ',' . &rtp

autocmd VimEnter * source ~/.vim/after/settings/lsp.vim

filetype plugin indent on
syntax on

" options go here
set hidden
```

with ` ~/.vim/after/settings/lsp.vim` reading

``` vim
let lspOpts = #{
  \   autoComplete: v:false,
  \ }
call LspOptionsSet(lspOpts)

let lspServers = []
if filereadable($HOME . '/.local/bin/pylsp')
  call add(lspServers, #{name: 'pylsp',
                      \  filetype: 'python',
                      \  path: $HOME . '/.local/bin/pylsp',
                      \  args: ['--check-parent-process', '--verbose']
                      \ })
endif
call LspAddServer(lspServers)
```

and typing `print(<c-x><c-o>` inside a `*.py` file shows the error message

```vim
Trovato errore eseguendo function LspOmniFunc:
riga   43:
E716: Chiave assente dal Dizionario: "omniCompleteKeyword"
```

If instead `print<c-x><c-o>(<c-x><c-o>` then `print(` is completed to `print(print`

**Comment by yegappan** [comment] 2024-02-26 16:09
Thanks for the detailed steps.  I am able to reproduce the problem now.  This is a regression caused by the PR #418.  I have committed 0b9bba0ee4eaa84a75d88a0775b3b34dbf42b12d to address this issue.  Can you try the latest plugin?

**Comment by Konfekt** [comment] 2024-02-26 18:51
Thank you! Now it works without errors and does not insert text.

**Closed** 2024-02-26 20:55 UTC
