### ISSUE TITLE
"range" error deno

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#354] opened 2023-07-02 09:15 UTC
https://github.com/yegappan/lsp/assets/21293376/3af552bc-c5d0-4436-84f1-1882f479c407

**Comment by yegappan** [comment] 2023-07-04 14:33
Can you collect the output of the `:messages` command after this error is seen?  The recording video shows only the error and not the line in the plugin.

**Comment by maximyurevich** [comment] 2023-07-04 15:00
> Can you collect the output of the `:messages` command after this error is seen? The recording video shows only the error and not the line in the plugin.
![Screenshot_2023-07-04_17-57-42](https://github.com/yegappan/lsp/assets/21293376/d35554e6-fa96-4ea3-92db-afa2790fbe03)

**Comment by yegappan** [comment] 2023-07-04 17:47
I have committed b8a3771 to address this issue.  Can you try the latest version of the plugin and confirm whether the problem is addressed?

**Closed** 2023-07-04 17:46 UTC

**Comment by maximyurevich** [comment] 2023-07-04 18:59
> I have committed [b8a3771](https://github.com/yegappan/lsp/commit/b8a37710852c43f1f9bee88b086810e7f0869d29) to address this issue. Can you try the latest version of the plugin and confirm whether the problem is addressed?

Problem solved
